### ISSUE TITLE
Microsoft.Azure.Cosmos.Table is deprecated in favor of Azure.Data.Tables

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Persistence.AzureTable#386]
[Azure.Data.Tables](https://www.nuget.org/packages/Azure.Data.Tables) is replacing the currently used [Microsoft.Azure.Cosmos.Table](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table). It has been [announced](https://devblogs.microsoft.com/azure-sdk/azure-tables-client-libraries/) not long ago that the plan is to consolidate Table Storage and Cosmos DB Table API SDKs into one under the Azure SDK roof.

**Related issues**:
- https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/541
- https://github.com/Particular/TimeoutMigrationTool/issues/200

**Comment by SeanFeldman** [comment]
`Azure.Data.Tables` stable is [out](https://devblogs.microsoft.com/azure-sdk/announcing-the-new-azure-data-tables-libraries/).

**Comment by vince-nyanga** [comment]
Is there something in the pipeline to support the new SDK? I need to connect to Table Storage using managed identities and that doesn't seem to be possible on the old SDK.

**Comment by lailabougria** [comment]
Hey @vince-nyanga, thanks for the feedback. We're currently working on the upgrade, we'll keep you updated.

**Comment by lailabougria** [comment]
Done in https://github.com/Particular/NServiceBus.Persistence.AzureTable/pull/654

This will be released as part of NServiceBus.Persistence.AzureTable v5. Although v4 is not out yet, it was RC when this change was made, and we didn't want to introduce breaking changes into the RC'ed version.
To not further delay the support for the new Azure SDK, v5 will be released shortly after v4. We will ping again here once the new package is available.

**Comment by vince-nyanga** [comment]
Thank you!
