### ISSUE TITLE
Azure.Data.Tables replacing  Microsoft.Azure.Cosmos.Table

### ISSUE THREAD

**Issue by SeanFeldman** [Particular/NServiceBus.Persistence.AzureTable#601]
When `NServiceBus.Persistence.AzureStorage` was refreshed to work with Table Storage and Cosmos DB Table API, the new SDK for Table Storage (`Azure.Data.Tables`) wasn't GA-ed yet. A [tracking issue](https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/386) was raised to keep an eye on the upcoming `Azure.Data.Tables` SDK. The new Table Storage SDK is out, compatible with Cosmos DB Table API as well.

**Comment by DavidBoike** [comment]
I know this issue was transferred from another repo, and that's probably the reason, but isn't this a duplicate of https://github.com/Particular/NServiceBus.Persistence.AzureTable/issues/386 ?

**Comment by kbaley** [comment]
Agreed. Closing
